[package]
name = "worley-particle"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
image = "0.25.5"
tiny-skia = "0.11.4"

[dependencies]
contour-isobands = { version = "0.4.3", features =  ["parallel"] }
rand = "0.8.5"
thiserror = "2.0.9"
